Combos creation
Pletenica/SunflowerProject pull request #12
Opened 2023-10-05 12:33 UTC by Arnau77

Creation of the different combos for the different worlds and define every final combo for every world with its collision box. Create the system to use skills (without cooldowns). Add the status effects' system. Add ignited, weakened and slowed status effects.

2023-10-05 14:02 UTC, daskza19 commented
I think there's a problem with my branch and yours. It is not normal that all my changes are inside your pr too. Viewing your commits i see that ([this](https://github.com/Pletenica/SunflowerProject/pull/12/commits/31dc346051fbd9e034980ef98b094fb1f492a01d)) has all changes. Can we see in the future the way you manage conflicts? It's dificult to me see this PR with all changes from two features... (113 files)

2023-10-05 14:20 UTC, daskza19 requested changes

2023-10-05 14:20 UTC, daskza19 commented on Sunflower Project/Assets/Scripts/Character/ST_Entity.cs
> +        statusEffectsInfo = Resources.Load<ST_StatusEffectsInfo>("SO_StatusEffectsInfo");
I think we can separate the status effects with a new class that can be not monobehaviour. In this class we can store the actual status effect from the entity. Is sufficient independ from the rest of logic of the entity.

2023-10-05 14:20 UTC, daskza19 commented on Sunflower Project/Assets/Scripts/Managers/ST_GameManager.cs
> +        world = newWorld;
I think we can create an Event that will be Invoke in this method. All the GO that will be affected by world changing can be suscribed in there.

2023-10-05 14:38 UTC, Arnau77 commented on Sunflower Project/Assets/Scripts/Managers/ST_GameManager.cs
> +        world = newWorld;
This function will change in the future (when change of world is implemented), however, this comment is already as a TODO comment to take into account when changing the function.

2023-10-10 12:51 UTC, daskza19 approved these changes

2023-10-10 14:43 UTC, merged