Health system & Lostril Creation
Pletenica/SunflowerProject pull request #8
Opened 2023-08-09 16:09 UTC by Arnau77

Menu is opened, closed and interacted with using actions, also, when the menu is opened, the game pauses.
Health system implemented including death of player and resetting the game when that happens.
Mana usage and health recovery implemented.
Debug manager and game manager created.
Lostril creation (movement, changing states, damaging player, getting damage, dying & getting pushed).
Respawn in playroom implemented

2023-08-09 17:46 UTC, daskza19 commented
I found playing with this branch that if Lostril is respawned and the player are already in the area, the state of the Lostril is Wandering, is this intended? @Rugiacreed

2023-08-11 16:23 UTC, daskza19 requested changes

2023-08-11 16:40 UTC, Arnau77 commented on Sunflower Project/Assets/Scripts/Character/ST_CharacterCollision.cs
> +public class ST_CharacterCollision : MonoBehaviour
Done

2023-08-11 16:40 UTC, Arnau77 commented on Sunflower Project/Assets/Scripts/Managers/ST_DebugManager.cs
> +
Done

2023-08-11 16:48 UTC, Arnau77 commented on Sunflower Project/Assets/Scripts/Managers/ST_TextManager.cs
> +        Debug.Log(translatedDictionary[1].catText);
Deleted

2023-08-11 16:51 UTC, Arnau77 commented on Sunflower Project/Assets/Scripts/Skills/Templates/ST_SkillTreeNode.cs
> +    public void Buy()
Done

2023-08-11 17:08 UTC, Arnau77 commented on Sunflower Project/Assets/Scripts/Skills/Basic Attack/ST_BasicAttack.cs
> +        Vector3 position = ST_Player.instance.GetPosition();
This will be implemented in a future when we have the animations of attack

2023-08-11 17:08 UTC, Arnau77 commented on Sunflower Project/Assets/Scripts/Skills/Basic Attack/ST_BasicAttack.cs
> +            damageSkill.damage = damage + damage * 0.5f;
Done

2023-08-11 18:25 UTC, daskza19 approved these changes

2023-08-11 19:38 UTC, merged